package com.example.techuni.navigation

const val ROUTE_REGISTER="registration"
const val ROUTE_LOGIN="login"
const val ROUTE_HOME="home"
const val ROUTE_ABOUTSCREEN="about"
const val ROUTE_UNIVERSITY_PLAY_POLICY="university"
const val ROUTE_HOSTELS="hostels"
const val ROUTE_PHOTOSTAKEN="photo"
const val ROUTE_CONFRENCESCREEN="confrence"
const val ROUTE_NEWS="news"
const val ROUTE_SCHOOLS="schools"
const val ROUTE_STUDENTCOUNCIL="student"
const val ROUTE_SPLASH="splash"
const val ROUTE_MUTUAS="mumias"
const val ROUTE_VIDEOSCREEN="video"
const val ROUTE_EVENTS="events"
const val ROUTE_NOTICES="notices"
const val ROUTE_ADD="add"
const val ROUTE_MYAPP="myapp"
const val ROUTE_EVENTLIST="list"
const val ROUTE_ADDEVENT="add"
